name: Run Automation Script Every Day at 8AM

on:
  schedule:
    - cron: '0 3 * * *'  # 6h UTC = 8h heure française
  workflow_dispatch:      # permet de le lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter le script Python
        run: python Automation.py
